# Generated by Django 5.2.8 on 2025-11-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyzedShot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=255)),
                ('start_frame', models.IntegerField()),
                ('ball_bboxes', models.JSONField()),
                ('hoop_bbox', models.JSONField()),
                ('actual_angle', models.FloatField()),
                ('actual_velocity', models.FloatField()),
                ('optimal_angle', models.FloatField()),
                ('optimal_velocity', models.FloatField()),
                ('px_per_meter', models.FloatField()),
                ('start_pos_x', models.IntegerField()),
                ('start_pos_y', models.IntegerField()),
            ],
        ),
    ]
