# Generated by Django 5.2.8 on 2025-11-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyzedshot',
            name='end_frame',
            field=models.IntegerField(default=0),
        ),
    ]
